# github action ci/cd to build and deploy using scp
name: Deploy

on:
  push:
    branches:
      - master-{x}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/${{ secrets.PROJECT }}
            git pull
            sudo npm i
            sudo npm run build
            pm2 restart 1
